// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:a61097e6-6170-4c04-b2e6-448452c4f914',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'andrewsadmin-hosting-mobilehub-540552369',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1w5cizpg7lu73.cloudfront.net',
    'aws_mobile_analytics_app_id': '13bf57431980460885f8c13f975bb348',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'add1e52b-5eb9-46d8-af8f-3453bda9b0ea',
    'aws_project_name': 'andrews-admin',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'andrewsadmin-mobilehub-540552369',
}

export default awsmobile
