// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"5aw6bjwi0d","name":"Andrews Apis","description":"andrews admin apis","endpoint":"https://5aw6bjwi0d.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123","/path-7c8","/path-7c8/123","/path-7ca","/path-7ca/123","/path-7cc","/path-7cc/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:bef89f68-cbc6-4f96-b7b9-516398941452',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'andrewsadminapp-hosting-mobilehub-1405917934',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2oo75np99839y.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '9e97adaa54c54bf8a55c03ac2a483b06',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '2ea60518-02da-4e73-8378-0f0600a04d4a',
    'aws_project_name': 'andrews-admin-app',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'andrewsadminapp-deployments-mobilehub-1405917934',
    'aws_resource_name_prefix': 'andrewsadminapp-mobilehub-1405917934',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'andrewsadminapp-userfiles-mobilehub-1405917934',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_LDuyTsU9m',
    'aws_user_pools_web_client_id': '72pmbieu5hu95fgt21up8ecem1',
}

export default awsmobile;
